version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: testcase-postgres-dev
    environment:
      POSTGRES_DB: testcasemanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - testcase-network-dev
    restart: unless-stopped

  # Backend API (Development)
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend.dev
    container_name: testcase-backend-dev
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: testcasemanager
      DB_USER: postgres
      DB_PASSWORD: postgres123
      JWT_SECRET: dev-jwt-secret-key
      JWT_EXPIRES_IN: 24h
      UPLOAD_DIR: uploads
      MAX_FILE_SIZE: 10485760
    ports:
      - "3001:3001"
    volumes:
      - ../backend:/app
      - /app/node_modules
      - ../backend/uploads:/app/uploads
    depends_on:
      - postgres
    networks:
      - testcase-network-dev
    restart: unless-stopped
    command: npm run dev

  # Frontend Application (Development)
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend.dev
    container_name: testcase-frontend-dev
    environment:
      REACT_APP_API_URL: http://localhost:3001
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - testcase-network-dev
    restart: unless-stopped
    command: npm start

volumes:
  postgres_data_dev:
    driver: local

networks:
  testcase-network-dev:
    driver: bridge 